### ISSUE TITLE
In the subtitle list, align timestamps to the top instead of the middle.

### ISSUE THREAD

**Issue by max-kamps** [ripose-jp/Memento#193]
When subtitles span multiple lines, it can be hard to tell where one subtitle line begins and another ends.

![image](https://github.com/ripose-jp/Memento/assets/11182284/3ae7fa33-2c3f-40fd-ba71-b0f9eb35b89c)

If the timestamp was aligned to the top instead, it would align with the *start* of the subtitle text. (Which makes more sense)

![image](https://github.com/ripose-jp/Memento/assets/11182284/7f420edd-e9be-4a3e-a192-30e9d9903563)

**Comment by ripose-jp** [comment]
I'm not going to change the current behavior since English language fonts tend to be shorter than Japanese language fonts, so it ends up making the timestamps appear higher up than they should be. This problem doesn't exist when aligning them in the center.

![image](https://github.com/ripose-jp/Memento/assets/72582120/86da6d0d-54f1-4bc8-96f5-9383e1926d27)

If you need more delineation between rows, you can add stuff like this to your style sheets under **Interface** settings. Change the colors however you like.

```css
QTableView::item {
    border-top: 1px solid gray;
    border-bottom: 1px solid gray;
}

QTableView::item::selected {
    background-color: #346e8e;
}
```

![image](https://github.com/ripose-jp/Memento/assets/72582120/4fffd1e0-2d6c-415c-8f91-ccff92b047ce)
